export const fisetinDeepDiveDurationInFrames = 6800;

export const fisetinDeepDiveVoicePlaybackRate = 0.88;

export const fisetinDeepDiveSources = [
{
    label: "Yousefzadeh et al.",
    year: "2018",
    finding: "Zell- und Tierdaten: Fisetin wirkte senotherapeutisch; noch kein Human-Wirkversprechen.",
  },
{
    label: "Pilotstudie",
    year: "2024",
    finding: "Kleine Human-Pilotdaten zu biologischen Altersmarkern; vorläufig einordnen.",
  },
{
    label: "ClinicalTrials.gov",
    year: "laufend",
    finding: "Mehrere Studien prüfen Nutzen, Dosis und Sicherheit beim Menschen.",
  },
{
    label: "Review",
    year: "2024",
    finding: "Übersicht: spannend, aber Human-Evidenz und Dosierungsfragen bleiben offen.",
  }
] as const;

export const fisetinDeepDiveScenes = [
{
    image: "pexels/fisetin-v1/01-strawberries.jpg",
    secondaryImage: "pexels/fisetin-v1/03-microscope.jpg",
    eyebrow: "Gesundheits-Wissen",
    title: "Fisetin einfach erklärt",
    subtitle: "Was es ist, warum Zombie-Zellen Thema sind und wo der Hype zu weit geht.",
    mode: "problemSolution",
    accent: "gold",
    bullets: ["Pflanzenstoff", "Problem: Hype", "Lösung: Belege prüfen"],
    sourceIndex: 0,
    audio: "audio/fisetin-deepdive-normalos/scene-01-aoede.wav",
    audioSeconds: 19.051,
    start: 0,
    duration: 687,
  },
{
    image: "pexels/fisetin-v1/02-strawberry-source.jpg",
    secondaryImage: "pexels/fisetin-v1/06-polyphenol-foods.jpg",
    eyebrow: "Was ist es?",
    title: "Ein gelber Pflanzenstoff",
    subtitle: "Fisetin gehört zu den Flavonolen: Schutzstoffe aus Pflanzen, nicht automatisch ein Medikament.",
    mode: "molecule",
    accent: "berry",
    bullets: ["Formel: C15H10O6", "In Erdbeeren", "Auch in Pflanzen"],
    sourceIndex: 0,
    audio: "audio/fisetin-deepdive-normalos/scene-02-aoede.wav",
    audioSeconds: 19.211,
    start: 687,
    duration: 693,
  },
{
    image: "pexels/fisetin-v1/03-microscope.jpg",
    secondaryImage: "pexels/fisetin-v1/08-research.jpg",
    eyebrow: "Einfach erklärt",
    title: "Zombie-Zellen = müde Zellen",
    subtitle: "Sie teilen sich kaum noch, können aber störende Entzündungssignale senden.",
    mode: "senescence",
    accent: "slate",
    bullets: ["alt und träge", "Signalstoffe", "Forschungsthema"],
    sourceIndex: 0,
    audio: "audio/fisetin-deepdive-normalos/scene-03-aoede.wav",
    audioSeconds: 18.811,
    start: 1380,
    duration: 679,
  },
{
    image: "pexels/fisetin-v1/08-research.jpg",
    secondaryImage: "pexels/fisetin-v1/03-microscope.jpg",
    eyebrow: "Senolytikum?",
    title: "Aufräumen klingt gut",
    subtitle: "Senolytisch heißt: alte Problemzellen gezielt entfernen. Beim Menschen ist das noch nicht bewiesen.",
    mode: "senolytic",
    accent: "green",
    bullets: ["erkennen", "entfernen", "noch Forschung"],
    sourceIndex: 0,
    audio: "audio/fisetin-deepdive-normalos/scene-04-aoede.wav",
    audioSeconds: 18.251,
    start: 2059,
    duration: 660,
  },
{
    image: "pexels/fisetin-v1/01-strawberries.jpg",
    secondaryImage: "pexels/fisetin-v1/06-polyphenol-foods.jpg",
    eyebrow: "Food first",
    title: "Erdbeeren sind kein Protokoll",
    subtitle: "Lebensmittel liefern Fisetin, aber in kleinen Mengen und zusammen mit vielen anderen Stoffen.",
    mode: "foods",
    accent: "berry",
    bullets: ["Erdbeeren", "Äpfel", "Zwiebeln"],
    sourceIndex: 0,
    audio: "audio/fisetin-deepdive-normalos/scene-05-aoede.wav",
    audioSeconds: 19.891,
    start: 2719,
    duration: 716,
  },
{
    image: "pexels/fisetin-v1/07-biohacking.jpg",
    secondaryImage: "pexels/fisetin-v1/08-research.jpg",
    eyebrow: "Problem",
    title: "Mäusestudie ist kein Menschenbeweis",
    subtitle: "Die spannendsten Daten sind präklinisch. Humanstudien laufen, viele Fragen sind offen.",
    mode: "evidence",
    accent: "teal",
    bullets: ["Tierdaten spannend", "Menschen-Daten früh", "keine Garantie"],
    sourceIndex: 1,
    audio: "audio/fisetin-deepdive-normalos/scene-06-aoede.wav",
    audioSeconds: 18.851,
    start: 3435,
    duration: 681,
  },
{
    image: "pexels/fisetin-v1/05-capsules.jpg",
    secondaryImage: "pexels/fisetin-v1/07-biohacking.jpg",
    eyebrow: "Problem / Lösung",
    title: "Mehr Kapseln lösen es nicht",
    subtitle: "Bei Fisetin ist unklar, welche Dosis für wen sinnvoll, wirksam und langfristig sicher ist.",
    mode: "dose",
    accent: "clay",
    bullets: ["Dosis offen", "Qualität prüfen", "ärztlich denken"],
    sourceIndex: 2,
    audio: "audio/fisetin-deepdive-normalos/scene-07-aoede.wav",
    audioSeconds: 18.611,
    start: 4116,
    duration: 672,
  },
{
    image: "pexels/fisetin-v1/05-capsules.jpg",
    secondaryImage: "pexels/fisetin-v1/01-strawberries.jpg",
    eyebrow: "Wenn Supplement",
    title: "Sauber statt laut",
    subtitle: "Klare Milligramm-Angabe, transparente Herkunft und wenige Zusatzstoffe sind wichtiger als Werbesprache.",
    mode: "quality",
    accent: "green",
    bullets: ["mg klar", "Reinheit", "kein Heilversprechen"],
    sourceIndex: 3,
    audio: "audio/fisetin-deepdive-normalos/scene-08-aoede.wav",
    audioSeconds: 18.771,
    start: 4788,
    duration: 678,
  },
{
    image: "pexels/fisetin-v1/04-healthy-aging.jpg",
    secondaryImage: "pexels/fisetin-v1/05-capsules.jpg",
    eyebrow: "Sicherheit",
    title: "Nicht für jeden einfach nehmen",
    subtitle: "Schwangerschaft, Medikamente, Immunsystem, OPs oder Erkrankungen vorher abklären.",
    mode: "safety",
    accent: "clay",
    bullets: ["Schwangerschaft", "Medikamente", "Erkrankungen"],
    sourceIndex: 2,
    audio: "audio/fisetin-deepdive-normalos/scene-09-aoede.wav",
    audioSeconds: 17.771,
    start: 5466,
    duration: 644,
  },
{
    image: "pexels/fisetin-v1/04-healthy-aging.jpg",
    secondaryImage: "pexels/fisetin-v1/01-strawberries.jpg",
    eyebrow: "Kurzfazit",
    title: "Spannender Kandidat, keine Abkürzung",
    subtitle: "Fisetin bleibt interessant. Die Basis bleibt Ernährung, Bewegung, Schlaf und Stressregulation.",
    mode: "summary",
    accent: "gold",
    bullets: ["einfach verstehen", "Hype bremsen", "Basis zuerst"],
    sourceIndex: 3,
    audio: "audio/fisetin-deepdive-normalos/scene-10-aoede.wav",
    audioSeconds: 18.451,
    start: 6110,
    duration: 690,
  }
] as const;
