export const fisetinAffiliateUrl = 'https://amzn.to/4tCefvK';

export const fisetinDurationInFrames = 3660;

export const fisetinSources = [
  {
    label: 'Yousefzadeh et al.',
    year: '2018',
    url: 'https://pubmed.ncbi.nlm.nih.gov/30279143/',
    finding: 'Fisetin zeigte in präklinischen Modellen senotherapeutische Effekte.',
  },
  {
    label: 'Pilotstudie',
    year: '2024',
    url: 'https://pubmed.ncbi.nlm.nih.gov/39269340/',
    finding: 'Erste Human-Daten prüfen biologische Alterungsmarker, bleiben aber vorläufig.',
  },
  {
    label: 'Review',
    year: '2024',
    url: 'https://pubmed.ncbi.nlm.nih.gov/39384074/',
    finding: 'Weitere Humanstudien sind für Sicherheit, Dosis und Wirksamkeit nötig.',
  },
] as const;

export const fisetinScenes = [
  {
    start: 0,
    duration: 366,
    image: 'pexels/fisetin-v1/01-strawberries.jpg',
    eyebrow: 'Longevity / Biohacking',
    title: 'Fisetin im Check',
    subtitle: 'Der pflanzliche Stoff hinter dem Senolytika-Hype.',
    mode: 'hero',
    accent: 'berry',
  },
  {
    start: 366,
    duration: 366,
    image: 'pexels/fisetin-v1/03-microscope.jpg',
    eyebrow: 'Seneszente Zellen',
    title: 'Wenn Zellen nicht mehr sauber arbeiten',
    subtitle: 'Alternde Zellen können Entzündungssignale senden.',
    mode: 'senescence',
    accent: 'slate',
  },
  {
    start: 732,
    duration: 366,
    image: 'pexels/fisetin-v1/08-research.jpg',
    eyebrow: 'Senolytika',
    title: 'Zellulärer Frühjahrsputz?',
    subtitle: 'Fisetin wird als natürlicher Kandidat intensiv erforscht.',
    mode: 'senolytic',
    accent: 'gold',
  },
  {
    start: 1098,
    duration: 366,
    image: 'pexels/fisetin-v1/02-strawberry-source.jpg',
    eyebrow: 'Natürliches Flavonol',
    title: 'Erdbeeren sind der Ursprung',
    subtitle: 'Auch Äpfel, Zwiebeln, Gurken und Trauben enthalten Fisetin.',
    mode: 'foods',
    accent: 'berry',
  },
  {
    start: 1464,
    duration: 366,
    image: 'pexels/fisetin-v1/07-biohacking.jpg',
    eyebrow: 'Evidenz',
    title: 'Stark präklinisch. Human-Daten früh.',
    subtitle: 'Spannend, aber kein bewiesenes Anti-Aging-Versprechen.',
    mode: 'evidence',
    accent: 'teal',
  },
  {
    start: 1830,
    duration: 366,
    image: 'pexels/fisetin-v1/04-healthy-aging.jpg',
    eyebrow: 'Die Basis',
    title: 'Biohacking beginnt nicht mit Kapseln',
    subtitle: 'Schlaf, Training, Ernährung und Blutwerte zuerst.',
    mode: 'routine',
    accent: 'green',
  },
  {
    start: 2196,
    duration: 366,
    image: 'pexels/fisetin-v1/05-capsules.jpg',
    eyebrow: 'Supplement-Check',
    title: 'Qualität entscheidet',
    subtitle: 'Hochrein, transparent dosiert, vegan und möglichst wenig Zusätze.',
    mode: 'quality',
    accent: 'cream',
  },
  {
    start: 2562,
    duration: 366,
    image: 'pexels/fisetin-v1/06-polyphenol-foods.jpg',
    eyebrow: 'Wichtig',
    title: 'Nicht blind hochdosieren',
    subtitle: 'Medikamente, Blutverdünner, OPs oder Erkrankungen ärztlich abklären.',
    mode: 'safety',
    accent: 'clay',
  },
  {
    start: 2928,
    duration: 366,
    image: 'pexels/fisetin-v1/05-capsules.jpg',
    eyebrow: 'Anzeige / Affiliate',
    title: 'MoleQlar Fisetin',
    subtitle: 'Hochrein, vegan, GMO-frei und als Longevity-Baustein sauber eingeordnet.',
    mode: 'cta',
    accent: 'gold',
  },
  {
    start: 3294,
    duration: 366,
    image: 'pexels/fisetin-v1/01-strawberries.jpg',
    eyebrow: 'Kurz gesagt',
    title: 'Kein Zauber. Ein spannender Kandidat.',
    subtitle: 'Für Zellgesundheit, Seneszenz-Forschung und reflektiertes Biohacking.',
    mode: 'summary',
    accent: 'berry',
  },
] as const;
