export const momusExplainerDurationInFrames = 3300;

export const momusExplainerScenes = [
  {
    start: 0,
    duration: 360,
    eyebrow: 'App-Erklärvideo',
    title: 'MOMUS',
    subtitle: 'Der Energie-Kompass für deinen Alltag.',
    mode: 'hero',
    accent: 'gold',
    bullets: ['Energie erkennen', 'Lecks schließen', 'Lebenszeit zurückholen'],
  },
  {
    start: 360,
    duration: 420,
    eyebrow: 'Energy Cockpit',
    title: 'Dein Tag wird sichtbar',
    subtitle: 'Akku, Tagesintention und echte Einflussfaktoren auf einen Blick.',
    mode: 'cockpit',
    accent: 'emerald',
    bullets: ['Schlaf', 'Schritte', 'Sitzen', 'Bildschirmzeit'],
  },
  {
    start: 780,
    duration: 330,
    eyebrow: 'Micro-Lives',
    title: 'Gewohnheiten als Minuten',
    subtitle: 'MOMUS übersetzt Verhalten in kleine Zeitgewinne und Zeitverluste.',
    mode: 'microlife',
    accent: 'teal',
    bullets: ['+ Bewegung', '+ Schlaf', '- Dauerstress', '- Doomscrolling'],
  },
  {
    start: 1110,
    duration: 420,
    eyebrow: 'Leak-Finder',
    title: 'Wo verliert dein Tag Energie?',
    subtitle: 'Vier Leck-Kategorien machen versteckte Belastungen greifbar.',
    mode: 'leaks',
    accent: 'rust',
    bullets: ['Bildschirm', 'Social Load', 'Kopf-Chaos', 'Umgebung'],
  },
  {
    start: 1530,
    duration: 420,
    eyebrow: 'Phoenix Path',
    title: 'Neustart mit Score, Streak und XP',
    subtitle: 'Schritte, Screen Time, Lecks und Reflexion werden zu Fortschritt.',
    mode: 'phoenix',
    accent: 'gold',
    bullets: ['Phoenix-Score', 'XP bis 200/Tag', 'Wenn-Dann-Plan'],
  },
  {
    start: 1950,
    duration: 420,
    eyebrow: 'Analysen',
    title: 'KI-Auswertung ohne Datennebel',
    subtitle: 'Energy Lab, Handy-Analyse, Profil-Verlauf und PDF-Report.',
    mode: 'analyses',
    accent: 'blue',
    bullets: ['Wochencharts', 'Kategorien lokal', 'PDF Report'],
  },
  {
    start: 2370,
    duration: 300,
    eyebrow: 'Immer frei',
    title: 'Krisenmodus und Atmung',
    subtitle: 'Wenn es akut wird: Stabilisierung, Atemübungen und KI-Begleitung.',
    mode: 'crisis',
    accent: 'cream',
    bullets: ['2 Minuten', 'Atemtechniken', 'ohne Paywall'],
  },
  {
    start: 2670,
    duration: 360,
    eyebrow: 'Mehr Werkzeuge',
    title: 'Vom Food Scanner bis Brain Games',
    subtitle: 'Dokumente, Bibliothek, Barcode-Scan und 15 kognitive Mini-Spiele.',
    mode: 'tools',
    accent: 'emerald',
    bullets: ['Dokumente', 'Food Scanner', 'Bibliothek', 'Brain Games'],
  },
  {
    start: 3030,
    duration: 270,
    eyebrow: 'Callidus Ökosystem',
    title: 'NEXUS, MOMUS, KAIROS',
    subtitle: 'Körperdaten, Energie-Signale und Kontext wachsen zusammen.',
    mode: 'ecosystem',
    accent: 'gold',
    bullets: ['NEXUS', 'MOMUS', 'KAIROS'],
  },
] as const;

export const momusExplainerChapters = [
  'Cockpit',
  'Micro-Lives',
  'Leaks',
  'Phoenix',
  'Analysen',
  'Krisenmodus',
  'Tools',
  'Ökosystem',
] as const;
