export const proteinPowerDurationInFrames = 2400;

export const proteinPowerScenes = [
  {
    start: 0,
    duration: 270,
    image: 'generated/protein-ad/01-protein-product.png',
    eyebrow: 'Protein',
    title: 'Kein Zauberpulver',
    subtitle: 'Aber ein Baustein, den dein Körper jeden Tag braucht.',
    align: 'top',
    chips: ['Alltag', 'Training', 'Ernährung'],
  },
  {
    start: 270,
    duration: 330,
    image: 'generated/protein-ad/02-workout-shaker.png',
    eyebrow: 'Baustein',
    title: 'Aminosäuren für Struktur',
    subtitle: 'Muskeln, Gewebe, Enzyme, Hormone und Regeneration.',
    align: 'top',
    chips: ['Muskeln', 'Gewebe', 'Regeneration'],
  },
  {
    start: 600,
    duration: 360,
    image: 'generated/protein-ad/03-food-first.png',
    eyebrow: 'Referenzwert',
    title: '0,8 g pro kg',
    subtitle: 'DGE-Referenzwert für Erwachsene. Ab 65 Jahren: 1,0 g pro kg.',
    align: 'top',
    chips: ['DGE', 'pro Tag', 'individuell'],
    meter: true,
  },
  {
    start: 960,
    duration: 330,
    image: 'generated/protein-ad/03-food-first.png',
    eyebrow: 'Food first',
    title: 'Die Basis bleibt Essen',
    subtitle: 'Joghurt, Eier, Linsen, Tofu, Fisch, Fleisch, Nüsse und Getreide.',
    align: 'bottom',
    chips: ['Mahlzeiten', 'Vielfalt', 'Routine'],
  },
  {
    start: 1290,
    duration: 330,
    image: 'generated/protein-ad/01-protein-product.png',
    eyebrow: 'Praktisch',
    title: 'Wenn der Alltag eng wird',
    subtitle: 'Shake nach dem Training, im Frühstück oder als smarter Snack.',
    align: 'bottom',
    chips: ['Training', 'Frühstück', 'Snack'],
  },
  {
    start: 1620,
    duration: 330,
    image: 'generated/protein-ad/01-protein-product.png',
    eyebrow: 'Kauf-Check',
    title: 'Nicht blind kaufen',
    subtitle: 'Protein pro Portion, kurze Zutatenliste, wenig Zucker, guter Geschmack.',
    align: 'top',
    chips: ['Protein', 'Zutaten', 'Zucker'],
    checklist: true,
  },
  {
    start: 1950,
    duration: 450,
    image: 'generated/protein-ad/02-workout-shaker.png',
    eyebrow: 'Anzeige',
    title: 'Empfehlung in der Beschreibung',
    subtitle: 'Affiliate-Link einfügen und den passenden Protein-Typ wählen.',
    align: 'bottom',
    chips: ['Link', 'Beschreibung', 'Callidus A&M'],
  },
] as const;
