export const proteinSatireDurationInFrames = 2070;

export const proteinSatireScenes = [
  {
    start: 0,
    duration: 255,
    image: 'generated/protein-satire/01-protein-lab-satire.png',
    eyebrow: 'Momus-Modus',
    title: 'Protein als Charaktertest',
    subtitle: 'Willkommen im Zeitalter der Scoop-Religion.',
    align: 'top',
    chips: ['Shaker-Pflicht', 'Scoop-Aura', 'Frühstücksaudit'],
    panel: 'satire',
  },
  {
    start: 255,
    duration: 255,
    image: 'generated/protein-satire/01-protein-lab-satire.png',
    eyebrow: 'Satire',
    title: 'Die Waage wird zum Altar',
    subtitle: 'Und der Haferbrei möchte einfach nur Frühstück sein.',
    align: 'bottom',
    chips: ['Altar', 'Hostie', 'Hype'],
    panel: 'satire',
  },
  {
    start: 510,
    duration: 240,
    image: 'generated/protein-satire/02-amino-construction.png',
    eyebrow: 'Bruch',
    title: 'Spaß beiseite.',
    subtitle: 'Protein ist kein Zauber. Es ist Baustoff.',
    align: 'top',
    chips: ['Muskeln', 'Gewebe', 'Enzyme'],
    panel: 'amino',
  },
  {
    start: 750,
    duration: 260,
    image: 'generated/protein-satire/02-amino-construction.png',
    eyebrow: 'Aminosäuren',
    title: 'Aus Eiweiß werden Bausteine',
    subtitle: 'Der Körper zerlegt Protein und baut daraus Struktur.',
    align: 'top',
    chips: ['EAAs', 'Leucin', 'Reparatur'],
    panel: 'amino',
  },
  {
    start: 1010,
    duration: 270,
    image: 'generated/protein-satire/03-food-first-protein.png',
    eyebrow: 'Orientierung',
    title: 'Wie viel ist sinnvoll?',
    subtitle: 'DGE: 0,8 g/kg für Erwachsene. Ab 65: 1,0 g/kg als Schätzwert.',
    align: 'top',
    chips: ['DGE', 'pro Tag', 'individuell'],
    panel: 'numbers',
  },
  {
    start: 1280,
    duration: 260,
    image: 'generated/protein-satire/02-amino-construction.png',
    eyebrow: 'Training',
    title: 'Wer hart trainiert, braucht oft mehr',
    subtitle: 'ISSN: Für viele Trainierende liegt der Bereich bei 1,4 bis 2,0 g/kg.',
    align: 'bottom',
    chips: ['Training', 'Regeneration', 'Qualität'],
    panel: 'training',
  },
  {
    start: 1540,
    duration: 260,
    image: 'generated/protein-satire/03-food-first-protein.png',
    eyebrow: 'Food first',
    title: 'Die Basis bleibt Essen',
    subtitle: 'Hülsenfrüchte, Tofu, Eier, Joghurt, Fisch, Nüsse und Getreide.',
    align: 'top',
    chips: ['Vielfalt', 'Sättigung', 'Routine'],
    panel: 'food',
  },
  {
    start: 1800,
    duration: 270,
    image: 'generated/protein-satire/04-smart-product-choice.png',
    eyebrow: 'Anzeige',
    title: 'Nicht blind kaufen',
    subtitle: 'Hanfprotein, Aminosäuren-Komplex und EAA sind in der Beschreibung verlinkt.',
    align: 'bottom',
    chips: ['Protein', 'Zutaten', 'Verträglichkeit'],
    panel: 'products',
  },
] as const;
