export const q10AffiliateUrl = 'https://amzn.to/4wnlJVY';

export const q10DurationInFrames = 3420;

export const q10Sources = [
  {
    label: 'Bioverfügbarkeit',
    year: '2020',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7278738/',
    finding: 'Q10 ist fettlöslich; Aufnahme und Formulierung sind entscheidend.',
  },
  {
    label: 'Herzinsuffizienz',
    year: '2024',
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11515203/',
    finding: 'Metaanalyse von RCTs: Q10 wird als Zusatztherapie untersucht.',
  },
  {
    label: 'Statin-Myopathie',
    year: '2025',
    url: 'https://pubmed.ncbi.nlm.nih.gov/41158831/',
    finding: 'Systematische Auswertung: Daten zu Muskelsymptomen bleiben einzuordnen.',
  },
] as const;

export const q10Scenes = [
  {
    start: 0,
    duration: 342,
    image: 'pexels/q10-v1/01-mitochondria-lab.jpg',
    eyebrow: 'Wissenswertes',
    title: 'Coenzym Q10',
    subtitle: 'Der Zündfunke für deine zelluläre Energie.',
    mode: 'hero',
    accent: 'amber',
  },
  {
    start: 342,
    duration: 342,
    image: 'pexels/q10-v1/02-cell-science.jpg',
    eyebrow: 'Mitochondrien',
    title: 'Energie entsteht in der Zelle',
    subtitle: 'Q10 hilft in der Atmungskette bei der ATP-Produktion.',
    mode: 'mitochondria',
    accent: 'teal',
  },
  {
    start: 684,
    duration: 342,
    image: 'pexels/q10-v1/08-workout-recovery.jpg',
    eyebrow: 'ATP',
    title: 'Nicht Kick. Zellenergie.',
    subtitle: 'Q10 ist kein Energy-Drink, sondern ein Cofaktor.',
    mode: 'atp',
    accent: 'gold',
  },
  {
    start: 1026,
    duration: 342,
    image: 'pexels/q10-v1/04-heart-health.jpg',
    eyebrow: 'Hoher Bedarf',
    title: 'Herz, Muskeln, Gehirn',
    subtitle: 'Gewebe mit viel Energiebedarf brauchen stabile Zellkraftwerke.',
    mode: 'organs',
    accent: 'green',
  },
  {
    start: 1368,
    duration: 342,
    image: 'pexels/q10-v1/03-healthy-aging-energy.jpg',
    eyebrow: 'Healthy Aging',
    title: 'Warum Q10 ab 40 interessant wird',
    subtitle: 'Die körpereigene Produktion kann mit dem Alter nachlassen.',
    mode: 'aging',
    accent: 'amber',
  },
  {
    start: 1710,
    duration: 342,
    image: 'pexels/q10-v1/07-research.jpg',
    eyebrow: 'Evidenz',
    title: 'Gut erforscht, aber kein Allheilmittel',
    subtitle: 'Stärker im Herz-Kontext; Statin-Daten vorsichtig einordnen.',
    mode: 'evidence',
    accent: 'slate',
  },
  {
    start: 2052,
    duration: 342,
    image: 'pexels/q10-v1/05-capsules.jpg',
    eyebrow: 'Form',
    title: 'Ubiquinol oder Ubiquinon?',
    subtitle: 'Ubiquinol wird besonders ab 40 oft bevorzugt.',
    mode: 'forms',
    accent: 'cream',
  },
  {
    start: 2394,
    duration: 342,
    image: 'pexels/q10-v1/06-fatty-meal.jpg',
    eyebrow: 'Aufnahme',
    title: 'Mit Fett einnehmen',
    subtitle: 'Q10 ist fettlöslich. Die Mahlzeit macht einen Unterschied.',
    mode: 'absorption',
    accent: 'green',
  },
  {
    start: 2736,
    duration: 342,
    image: 'pexels/q10-v1/05-capsules.jpg',
    eyebrow: 'Anzeige / Affiliate',
    title: 'Callidus Empfehlung',
    subtitle: 'Coenzym Q10 als sauber eingeordneter Baustein für Zellenergie.',
    mode: 'cta',
    accent: 'gold',
  },
  {
    start: 3078,
    duration: 342,
    image: 'pexels/q10-v1/03-healthy-aging-energy.jpg',
    eyebrow: 'Kurz gesagt',
    title: 'Mitochondrien. Herz. Zellenergie.',
    subtitle: 'Q10 ist kein Hype, sondern ein biochemisch spannender Cofaktor.',
    mode: 'summary',
    accent: 'teal',
  },
] as const;
