export const sitePromoVoiceoverText =
  'Die neue Website von callidus A&M ist da. Ein klarer Kompass für deine Gesundheit. Du findest fundierte Ratgeber, kurze Checks, transparente Empfehlungen und App-Unterstützung an einem Ort. Die Themen sind sauber sortiert: Körper und Ernährung, Sport und Energie, Geist und Seele und die Zukunft der Gesundheit. Mit den 2-Minuten-Checks bekommst du Orientierung, ohne Diagnoseversprechen. In den Empfehlungen siehst du transparent gekennzeichnete Produkte und Tools. Im Portal wachsen NEXUS, MOMUS, KAIROS und der Coach zusammen. Mit VALUS und Wallet wird gesunde Routine sogar belohnbar. Und Wissenskarten, Quellen und Handbuch helfen dir, schneller zu verstehen. callidus A&M: Gesundheit, die man wirklich versteht.';

export const sitePromoScenes = [
  {
    start: 0,
    duration: 160,
    image: 'generated/site-promo/01-home.png',
    eyebrow: 'Neue Website',
    title: 'Ein klarer Kompass für deine Gesundheit.',
    subtitle: 'Wissen, Routinen, Empfehlungen und App-Unterstützung an einem Ort.',
    chips: ['Health Intelligence', 'Ratgeber', '2-Minuten-Checks'],
    align: 'bottom',
    tone: 'sage',
  },
  {
    start: 160,
    duration: 160,
    image: 'generated/site-promo/02-ratgeber.png',
    eyebrow: 'Ratgeber',
    title: 'Wissen nach Lebensbereichen sortiert.',
    subtitle: 'Körper, Sport, Geist und Zukunft: alles schneller auffindbar.',
    chips: ['Körper & Ernährung', 'Sport & Energie', 'Geist & Seele'],
    align: 'top',
    tone: 'teal',
  },
  {
    start: 320,
    duration: 160,
    image: 'generated/site-promo/04-checks.png',
    eyebrow: 'Checks',
    title: 'In zwei Minuten mehr Orientierung.',
    subtitle: 'Stress, Mikronährstoffe und Health IQ ohne Diagnoseversprechen.',
    chips: ['Sofort sichtbar', 'Lernen mit Quellen', 'Nächste Schritte'],
    align: 'bottom',
    tone: 'gold',
  },
  {
    start: 480,
    duration: 160,
    image: 'generated/site-promo/03-empfehlungen.png',
    eyebrow: 'Empfehlungen',
    title: 'Bewusst ausgewählt statt endlos gesucht.',
    subtitle: 'Produkte, Kurse und Tools sind transparent gekennzeichnet.',
    chips: ['Affiliate-Hinweis', 'Sortierte Bereiche', 'Alltagstauglich'],
    align: 'top',
    tone: 'clay',
  },
  {
    start: 640,
    duration: 160,
    image: 'generated/site-promo/05-portal.png',
    eyebrow: 'Portal',
    title: 'Dein System wächst zusammen.',
    subtitle: 'NEXUS, MOMUS, KAIROS und Coach greifen an einem Ort ineinander.',
    chips: ['NEXUS', 'MOMUS', 'KAIROS'],
    align: 'bottom',
    tone: 'teal',
  },
  {
    start: 800,
    duration: 160,
    image: 'generated/site-promo/06-apps.png',
    eyebrow: 'Apps',
    title: 'Begleiter für Routinen und Fortschritt.',
    subtitle: 'Klare Einstiege für Alltag, Wissen und persönliche Orientierung.',
    chips: ['Mobile App', 'Routinen', 'Coach'],
    align: 'top',
    tone: 'sage',
  },
  {
    start: 960,
    duration: 160,
    image: 'generated/site-promo/07-valus.png',
    eyebrow: 'VALUS',
    title: 'Gesunde Routine wird belohnbar.',
    subtitle: 'Wallet, Meilensteine und Gesundheitsökonomie verständlich gedacht.',
    chips: ['Wallet', 'Belohnung', 'Transparenz'],
    align: 'bottom',
    tone: 'gold',
  },
  {
    start: 1120,
    duration: 160,
    image: 'generated/site-promo/08-wissenskarten.png',
    eyebrow: 'Wissenskarten',
    title: 'Schneller verstehen. Besser einordnen.',
    subtitle: 'Kompakte Karten verbinden Begriffe, Quellen und nächste Schritte.',
    chips: ['Kompakt', 'Quellen', 'Verknüpft'],
    align: 'top',
    tone: 'clay',
  },
  {
    start: 1280,
    duration: 160,
    image: 'generated/site-promo/09-handbuch.png',
    eyebrow: 'Handbuch',
    title: 'Quellen, Methodik und Klarheit.',
    subtitle: 'Für alle, die wissen wollen, wie callidus A&M arbeitet.',
    chips: ['Methodik', 'Leitplanken', 'Vertrauen'],
    align: 'bottom',
    tone: 'teal',
  },
] as const;
