export const spermidinAffiliateUrl = 'https://amzn.to/3PnvOle';

export const spermidinDurationInFrames = 3540;

export const spermidinScenes = [
  {
    start: 0,
    duration: 292,
    image: 'pexels/spermidin-v1/01-wheat-germ.jpg',
    eyebrow: 'Longevity / Biohacking',
    title: 'Spermidin im Check',
    subtitle: 'Zellpflege, Autophagie und was wirklich dahinter steckt.',
    mode: 'hero',
    accent: 'gold',
  },
  {
    start: 292,
    duration: 292,
    image: 'pexels/spermidin-v1/02-microscope.jpg',
    eyebrow: 'Zellgesundheit',
    title: 'Autophagie: Zell-Recycling',
    subtitle: 'Beschädigtes wird abgebaut, recycelt und wiederverwendet.',
    mode: 'autophagy',
    accent: 'teal',
  },
  {
    start: 584,
    duration: 292,
    image: 'pexels/spermidin-v1/07-biohacking.jpg',
    eyebrow: 'Evidenz einordnen',
    title: 'Spannend. Nicht magisch.',
    subtitle: 'Mechanistik stark. Human-Daten noch vorsichtig bewerten.',
    mode: 'evidence',
    accent: 'slate',
  },
  {
    start: 876,
    duration: 292,
    image: 'pexels/spermidin-v1/03-healthy-aging.jpg',
    eyebrow: 'Die Basis',
    title: 'Longevity beginnt im Alltag',
    subtitle: 'Schlaf, Training, Ernährung und Stressregulation zuerst.',
    mode: 'foundation',
    accent: 'green',
  },
  {
    start: 1168,
    duration: 292,
    image: 'pexels/spermidin-v1/01-wheat-germ.jpg',
    eyebrow: 'Food first',
    title: 'Natürlich in Weizenkeimen',
    subtitle: 'Eine der bekanntesten natürlichen Spermidin-Quellen.',
    mode: 'foods',
    accent: 'gold',
  },
  {
    start: 1460,
    duration: 292,
    image: 'pexels/spermidin-v1/06-soybeans.jpg',
    eyebrow: 'Ernaehrung',
    title: 'Auch in Soja & Hülsenfrüchten',
    subtitle: 'Sinnvoller als Hype: ein echtes Ernährungsmuster.',
    mode: 'foods2',
    accent: 'green',
  },
  {
    start: 1752,
    duration: 292,
    image: 'pexels/spermidin-v1/05-mushrooms.jpg',
    eyebrow: 'Vielfalt',
    title: 'Pilze, Kaese, Vollwertkost',
    subtitle: 'Die Mischung zählt mehr als ein einzelnes Lebensmittel.',
    mode: 'foods3',
    accent: 'clay',
  },
  {
    start: 2044,
    duration: 292,
    image: 'pexels/spermidin-v1/04-capsules.jpg',
    eyebrow: 'Supplement-Check',
    title: 'Wenn Kapseln, dann sauber',
    subtitle: 'Standardisiert, laborgeprüft, klare Milligramm-Angabe.',
    mode: 'quality',
    accent: 'teal',
  },
  {
    start: 2336,
    duration: 292,
    image: 'pexels/spermidin-v1/08-breakfast.jpg',
    eyebrow: 'Biohacking ohne Hype',
    title: 'Ein Baustein. Kein Ersatz.',
    subtitle: 'Spermidin wirkt nur im Kontext deiner Routine sinnvoll.',
    mode: 'routine',
    accent: 'cream',
  },
  {
    start: 2628,
    duration: 292,
    image: 'pexels/spermidin-v1/04-capsules.jpg',
    eyebrow: 'Wichtig',
    title: 'Verträglichkeit klären',
    subtitle: 'Bei Allergie, Schwangerschaft, Krankheit oder Medikamenten: ärztlich abklären.',
    mode: 'safety',
    accent: 'clay',
  },
  {
    start: 2920,
    duration: 292,
    image: 'pexels/spermidin-v1/01-wheat-germ.jpg',
    eyebrow: 'Anzeige / Affiliate',
    title: 'Callidus Empfehlung',
    subtitle: 'Natürlicher Weizenkeimextrakt, laborgeprüft, ohne unnötige Zusätze.',
    mode: 'cta',
    accent: 'gold',
  },
  {
    start: 3212,
    duration: 328,
    image: 'pexels/spermidin-v1/03-healthy-aging.jpg',
    eyebrow: 'Kurz gesagt',
    title: 'Kein Zaubertrick.',
    subtitle: 'Aber ein spannender Baustein für Zellgesundheit, Autophagie und Longevity.',
    mode: 'summary',
    accent: 'green',
  },
] as const;
