export const spermidinDeepDiveDurationInFrames = 6582;

export const spermidinDeepDiveVoicePlaybackRate = 0.88;

export const spermidinDeepDiveSources = [
{
    label: "JAMA Network Open",
    year: "2022",
    finding: "12 Monate: kein Vorteil bei Gedächtnis oder Biomarkern vs. Placebo.",
  },
{
    label: "Nutrients / PMC",
    year: "2023",
    finding: "15 mg/Tag erhöhten kurzfristig Plasma- oder Speichel-Spermidin nicht deutlich.",
  },
{
    label: "Nutrition Research",
    year: "2024",
    finding: "40 mg/Tag: minimale Effekte auf zirkulierende Polyamine.",
  },
{
    label: "ClinicalTrials.gov",
    year: "laufend",
    finding: "POLYCAD prüft kardiovaskuläre Fragen noch laufend.",
  }
] as const;

export const spermidinDeepDiveScenes = [
{
    image: "pexels/spermidin-v1/02-microscope.jpg",
    secondaryImage: "pexels/spermidin-v1/01-wheat-germ.jpg",
    eyebrow: "Gesundheits-Wissen",
    title: "Spermidin einfach erklärt",
    subtitle: "Was es ist, welches Problem der Hype macht und welche Lösung im Alltag Sinn ergibt.",
    mode: "problemSolution",
    accent: "gold",
    bullets: ["Was ist Spermidin?", "Problem: Hype", "Lösung: Food first"],
    audio: "audio/spermidin-deepdive-normalos/scene-01-aoede.wav",
    audioSeconds: 17.331,
    start: 0,
    duration: 629,
  },
{
    image: "pexels/spermidin-v1/07-biohacking.jpg",
    secondaryImage: "pexels/spermidin-v1/06-soybeans.jpg",
    eyebrow: "Was ist es?",
    title: "Ein kleiner Zellstoff",
    subtitle: "Spermidin gehört zu den Polyaminen: kleine Moleküle, die Zellen für Ordnung, Wachstum und Stoffwechsel nutzen.",
    mode: "molecule",
    accent: "teal",
    bullets: ["Formel: C7H19N3", "Im Körper vorhanden", "Auch in Lebensmitteln"],
    audio: "audio/spermidin-deepdive-normalos/scene-02-aoede.wav",
    audioSeconds: 21.651,
    start: 629,
    duration: 776,
  },
{
    image: "pexels/spermidin-v1/02-microscope.jpg",
    secondaryImage: "pexels/spermidin-v1/03-healthy-aging.jpg",
    eyebrow: "Einfach erklärt",
    title: "Autophagie = Zell-Recycling",
    subtitle: "Die Zelle räumt alten Ballast weg und nutzt brauchbare Teile wieder.",
    mode: "autophagy",
    accent: "green",
    bullets: ["Aufräumen", "Wiederverwerten", "Zelle im Gleichgewicht"],
    audio: "audio/spermidin-deepdive-normalos/scene-03-aoede.wav",
    audioSeconds: 18.571,
    start: 1405,
    duration: 671,
  },
{
    image: "pexels/spermidin-v1/08-breakfast.jpg",
    secondaryImage: "pexels/spermidin-v1/05-mushrooms.jpg",
    eyebrow: "Lösung im Alltag",
    title: "Erst Lebensmittel, dann Kapseln",
    subtitle: "Weizenkeime, Soja, Pilze, Hülsenfrüchte und gereifter Käse liefern Spermidin natürlicherweise.",
    mode: "foods",
    accent: "gold",
    bullets: ["Weizenkeime", "Soja und Hülsenfrüchte", "Pilze und Käse"],
    audio: "audio/spermidin-deepdive-normalos/scene-04-aoede.wav",
    audioSeconds: 19.811,
    start: 2076,
    duration: 713,
  },
{
    image: "pexels/spermidin-v1/03-healthy-aging.jpg",
    secondaryImage: "pexels/spermidin-v1/02-microscope.jpg",
    eyebrow: "Problem",
    title: "Hype ist kein Beweis",
    subtitle: "Nur weil ein Mechanismus plausibel klingt, ist ein Nutzen beim Menschen noch nicht bewiesen.",
    mode: "problemSolution",
    accent: "slate",
    bullets: ["Zell-Daten spannend", "Menschen-Daten vorsichtig", "Keine Verjüngungs-Garantie"],
    sourceIndex: 0,
    audio: "audio/spermidin-deepdive-normalos/scene-05-aoede.wav",
    audioSeconds: 15.931,
    start: 2789,
    duration: 581,
  },
{
    image: "pexels/spermidin-v1/04-capsules.jpg",
    secondaryImage: "pexels/spermidin-v1/01-wheat-germ.jpg",
    eyebrow: "Studien mit Menschen",
    title: "Placebo-Vergleiche bremsen den Hype",
    subtitle: "Mehrere Studien zeigen bisher begrenzte oder minimale Effekte. Das bremst die Werbeversprechen.",
    mode: "studies",
    accent: "teal",
    bullets: ["JAMA: kein klarer Gedächtnis-Vorteil", "Nutrients: Blutwerte nicht deutlich höher", "Nutrition Research: nur kleine Effekte"],
    sourceIndex: 1,
    audio: "audio/spermidin-deepdive-normalos/scene-06-aoede.wav",
    audioSeconds: 19.251,
    start: 3370,
    duration: 694,
  },
{
    image: "pexels/spermidin-v1/04-capsules.jpg",
    secondaryImage: "pexels/spermidin-v1/07-biohacking.jpg",
    eyebrow: "Problem / Lösung",
    title: "Mehr Kapseln lösen es nicht",
    subtitle: "Der Körper reguliert solche Zellstoffe eng. Die Lösung ist nicht automatisch eine höhere Dosis.",
    mode: "solution",
    accent: "clay",
    bullets: ["Dosis ist nicht Wirkung", "Etikett ist kein Beweis", "Ruhig und konservativ"],
    sourceIndex: 2,
    audio: "audio/spermidin-deepdive-normalos/scene-07-aoede.wav",
    audioSeconds: 16.651,
    start: 4064,
    duration: 606,
  },
{
    image: "pexels/spermidin-v1/01-wheat-germ.jpg",
    secondaryImage: "pexels/spermidin-v1/04-capsules.jpg",
    eyebrow: "Praktische Lösung",
    title: "Wenn Supplement, dann sauber",
    subtitle: "Transparente Herkunft, klare Milligramm-Angabe und Laborprüfung sind wichtiger als große Versprechen.",
    mode: "quality",
    accent: "green",
    bullets: ["Klare Milligramm-Angabe", "Qualität nachvollziehbar", "Wenig Zusatzstoffe"],
    audio: "audio/spermidin-deepdive-normalos/scene-08-aoede.wav",
    audioSeconds: 16.731,
    start: 4670,
    duration: 608,
  },
{
    image: "pexels/spermidin-v1/05-mushrooms.jpg",
    secondaryImage: "pexels/spermidin-v1/08-breakfast.jpg",
    eyebrow: "Sicherheit",
    title: "Vorher abklären, wenn Risiko besteht",
    subtitle: "Besonders bei Allergien, Schwangerschaft, Erkrankungen oder Medikamenten.",
    mode: "safety",
    accent: "clay",
    bullets: ["Weizenallergie beachten", "Schwangerschaft und Stillzeit", "Medikamente und Erkrankungen"],
    audio: "audio/spermidin-deepdive-normalos/scene-09-aoede.wav",
    audioSeconds: 17.091,
    start: 5278,
    duration: 621,
  },
{
    image: "pexels/spermidin-v1/03-healthy-aging.jpg",
    secondaryImage: "pexels/spermidin-v1/06-soybeans.jpg",
    eyebrow: "Kurzfazit",
    title: "Baustein, keine Abkürzung",
    subtitle: "Spermidin bleibt spannend. Die Basis bleibt aber Ernährung, Bewegung, Schlaf und Stressregulation.",
    mode: "summary",
    accent: "gold",
    bullets: ["Einfach verstehen", "Belege prüfen", "Basis zuerst"],
    sourceIndex: 3,
    audio: "audio/spermidin-deepdive-normalos/scene-10-aoede.wav",
    audioSeconds: 18.251,
    start: 5899,
    duration: 683,
  }
] as const;
