export const stressResetCourseDurationInFrames = 1790;

export const stressResetCourseScenes = [
  {
    start: 0,
    duration: 240,
    image: 'generated/stress-reset-course/01-daily-stress.png',
    eyebrow: 'Stress Reset',
    title: 'Du funktionierst. Aber dein System bleibt auf Alarm.',
    subtitle: 'Wenn der Tag vorbei ist, aber dein Kopf weiter rennt.',
    align: 'top',
    chips: ['Alarmmodus', 'Gedankendruck', 'innere Unruhe'],
    panel: 'alarm',
  },
  {
    start: 240,
    duration: 270,
    image: 'generated/stress-reset-course/03-course-mockup.png',
    eyebrow: '7-Tage Kurs',
    title: 'Ein sanfter Reset für deinen Alltag',
    subtitle: 'Callidus A&M begleitet dich mit Video, Journal und kleinen Übungen.',
    align: 'bottom',
    chips: ['Video', 'Journal', 'Praxis'],
    panel: 'course',
  },
  {
    start: 510,
    duration: 270,
    image: 'generated/stress-reset-course/02-breath-reset.png',
    eyebrow: 'Modul 1',
    title: 'Der Reset-Knopf',
    subtitle: 'Raus aus dem Stressmodus. Zurück in den Moment.',
    align: 'top',
    chips: ['Atmung', 'Wahrnehmen', 'Ankommen'],
    panel: 'breath',
  },
  {
    start: 780,
    duration: 270,
    image: 'generated/stress-reset-course/02-breath-reset.png',
    eyebrow: 'Selbstregulation',
    title: 'Nicht mehr nur reagieren',
    subtitle: 'Du übst, Reize bewusster zu verarbeiten und im Körper anzukommen.',
    align: 'bottom',
    chips: ['Präsenz', 'Klarheit', 'Ruhe'],
    panel: 'steps',
  },
  {
    start: 1050,
    duration: 270,
    image: 'generated/stress-reset-course/03-course-mockup.png',
    eyebrow: 'Dein Einstieg',
    title: 'Klein anfangen. Echt spüren.',
    subtitle: 'Eine Übung, ein Journal-Impuls, ein ruhiger nächster Schritt.',
    align: 'top',
    chips: ['1 Übung', '1 Impuls', '1 Schritt'],
    panel: 'steps',
  },
  {
    start: 1320,
    duration: 470,
    image: 'generated/stress-reset-course/03-course-mockup.png',
    eyebrow: 'Jetzt starten',
    title: 'Starte mit Modul 1',
    subtitle: 'callidus-am.de/stress-reset-kurs',
    align: 'bottom',
    chips: ['Webseite', 'Link in Bio', 'Beschreibung'],
    panel: 'course',
  },
] as const;
