export const valusXpVoiceoverText =
  'Was waere, wenn deine Gesundheitsroutine nicht nur sichtbar wird, sondern sich auch lohnt? Genau dafuer gibt es das XP- und VALUS-System von callidus A&M. Mit NEXUS sammelst du XP: durch Aktivitaet, Tracking und taegliche Routinen. 10000 XP koennen in 1 VAL umgewandelt werden. Und 1 VAL entspricht 1 Euro Rabatt auf Kurse, Premium-Inhalte und kommende Angebote. In der Wallet siehst du dein Guthaben und die naechsten Schritte. NEXUS ist der erste aktive Begleiter fuer Ernaehrung, Training, Regeneration und Tageswerte. MOMUS kommt als naechster Baustein dazu: mit Energie-Signalen, Phoenix-Werten und persoenlichem Kontext. Wichtig: VAL ist internes Guthaben, kein Investmentversprechen. callidus A&M: Gesundheit verstehen, Routinen aufbauen, Fortschritt belohnen.';

export const valusXpScenes = [
  {
    start: 0,
    duration: 160,
    image: 'generated/valus-xp-promo/01-valus-hero.png',
    eyebrow: 'XP + VALUS',
    title: 'Gesundheit, die sich lohnt.',
    subtitle: 'Routinen werden sichtbar. Fortschritt bekommt einen Wert.',
    mode: 'hero',
    accent: 'gold',
  },
  {
    start: 160,
    duration: 190,
    image: 'generated/valus-xp-promo/08-nexus-app.png',
    eyebrow: 'NEXUS',
    title: 'Deine Routine sammelt XP.',
    subtitle: 'Aktivitaet, Tracking und kleine Tagesgewohnheiten werden im System erfasst.',
    mode: 'app',
    accent: 'teal',
  },
  {
    start: 350,
    duration: 210,
    image: 'generated/valus-xp-promo/01-valus-hero.png',
    eyebrow: 'Umwandlung',
    title: '10000 XP werden zu 1 VAL.',
    subtitle: 'XP aus NEXUS-Aktivitaet kann in Valus-Guthaben umgerechnet werden.',
    mode: 'conversion',
    accent: 'gold',
  },
  {
    start: 560,
    duration: 170,
    image: 'generated/valus-xp-promo/01-valus-hero.png',
    eyebrow: 'Wert',
    title: '1 VAL = 1 Euro Rabatt.',
    subtitle: 'Einloesbar fuer Kurse, Premium-Inhalte und spaetere Angebote.',
    mode: 'value',
    accent: 'clay',
  },
  {
    start: 730,
    duration: 170,
    image: 'generated/valus-xp-promo/01-valus-hero.png',
    eyebrow: 'Wallet',
    title: 'Guthaben sehen. Schritte planen.',
    subtitle: 'Die Wallet macht VAL, XP und Einloesung uebersichtlich.',
    mode: 'wallet',
    accent: 'sage',
  },
  {
    start: 900,
    duration: 190,
    image: 'generated/valus-xp-promo/08-nexus-app.png',
    eyebrow: 'Aktiv',
    title: 'NEXUS ist der erste Begleiter.',
    subtitle: 'Ernaehrung, Training, Regeneration und Tageswerte laufen zusammen.',
    mode: 'nexus',
    accent: 'teal',
  },
  {
    start: 1090,
    duration: 190,
    image: 'generated/valus-xp-promo/06-momus-portal.png',
    eyebrow: 'Demnaechst',
    title: 'MOMUS erweitert den Kontext.',
    subtitle: 'Energie-Signale, Phoenix-Werte und Tagesmuster kommen nach dem Launch dazu.',
    mode: 'momus',
    accent: 'clay',
  },
  {
    start: 1280,
    duration: 250,
    image: 'generated/valus-xp-promo/01-valus-hero.png',
    eyebrow: 'callidus A&M',
    title: 'Verstehen. Aufbauen. Belohnen.',
    subtitle: 'Mehr zum System auf callidus-am.de/valus',
    mode: 'final',
    accent: 'gold',
  },
] as const;
