export const wmFocusVoiceoverText =
  'Kennst du das? Das Spiel f\u00e4ngt gleich an. Die Stimmung steigt, aber im Kopf h\u00e4ngt noch der ganze Tag. Bevor der Anpfiff kommt, nimm dir drei\u00dfig Sekunden. Atme vier Sekunden durch die Nase ein. Vier Sekunden halten. Vier Sekunden langsam ausatmen. Vier Sekunden halten. Box Breathing nennt man das. Es kann helfen, ruhiger zu werden und im Moment anzukommen. Denn echte St\u00e4rke, ob auf dem Platz oder vor dem Bildschirm, beginnt im Kopf. Dazu: Wasser bereitstellen, Snack bewusst w\u00e4hlen und kurz aufstehen, bevor es losgeht. Wenn du f\u00fcr die WM noch den passenden Deutschland-Look suchst: T-Shirt, Fu\u00dfball oder Fan-Accessoire verlinke ich dir in der Beschreibung. Anzeige. Jetzt Fokus an und Spiel genie\u00dfen.';

export const wmFocusScenes = [
  {
    start: 0,
    duration: 180,
    image: 'generated/wm-focus/01-shirt-hero.png',
    eyebrow: 'WM-Abend',
    title: 'Fokus vor dem Anpfiff',
    subtitle: 'Nicht nur Outfit. Auch der Kopf kommt an.',
    align: 'bottom',
    focus: 'center',
  },
  {
    start: 180,
    duration: 210,
    image: 'generated/wm-focus/02-breathing-focus.png',
    eyebrow: '30 Sekunden',
    title: 'Raus aus dem Tageschaos',
    subtitle: 'Kurz stoppen, bevor die Stimmung hochf\u00e4hrt.',
    align: 'bottom',
    focus: 'center',
  },
  {
    start: 390,
    duration: 360,
    image: 'generated/wm-focus/02-breathing-focus.png',
    eyebrow: 'Box Breathing',
    title: '4 - 4 - 4 - 4',
    subtitle: 'Einatmen. Halten. Ausatmen. Halten.',
    align: 'top',
    focus: 'center',
    breathing: true,
  },
  {
    start: 750,
    duration: 210,
    image: 'generated/wm-focus/04-stadium-shirt.png',
    eyebrow: 'Mindset',
    title: 'St\u00e4rke beginnt im Kopf',
    subtitle: 'Auf dem Platz und vor dem Bildschirm.',
    align: 'bottom',
    focus: 'center',
  },
  {
    start: 960,
    duration: 210,
    image: 'generated/wm-focus/03-healthy-matchnight.png',
    eyebrow: 'Gesunder Spielabend',
    title: 'Wasser. Snack. Bewegung.',
    subtitle: 'Kleine Routine, gro\u00dfer Unterschied.',
    align: 'bottom',
    focus: 'center',
  },
  {
    start: 1170,
    duration: 270,
    image: 'generated/wm-focus/01-shirt-hero.png',
    eyebrow: 'Deutschland-Look',
    title: 'T-Shirt, Ball, Accessoire?',
    subtitle: 'Affiliate-Links kommen in die Beschreibung.',
    align: 'bottom',
    focus: 'center',
  },
] as const;
